### ISSUE TITLE
建议看看能不能增加引入第三方库的功能

### ISSUE THREAD

**Issue by 0x0042** [laomao800/hexo-tag-demo#1]
这是一条手动点赞issue，附带一点小建议 @laomao800

**Comment by llp0574** [comment]
@laomao800 提出一点小建议

**Comment by 0x0042** [comment]
@laomao800 试了下原来是可以的。。。

**Comment by laomao800** [comment]
不知具体使用场景是怎么样的，不过发现了在 `<template>` 标签中书写 `<script>` 标签会导致展开演示中的 js 演示代码有获取错误的问题， https://github.com/laomao800/hexo-tag-demo/commit/5f0f7f1fc3ca2bd286f3bb3a5d0d098600a5b858 中已修复，第三方的 `<script>` 引用可直接写在 `<template>` 中。

---

另外由于本插件只是简单的插入代码段，如果单纯页面上需要引入第三方 js 库的话，避免重复引入导致重复加载的话，建议也可在文章顶部通过 [{% raw %}](https://hexo.io/zh-cn/docs/tag-plugins.html#Raw) 标签插入 js 或 css 标签引入第三方文件的形式来插入。

```
{% raw%}
<script src="a.js"></script>
<script src="b.js"></script>
{% endraw %}
```

如果引用的页面较多可考虑通过 [front-matter](https://hexo.io/zh-cn/docs/front-matter.html) 定义一个专用的 layout 。

**Comment by 0x0042** [comment]
@laomao800 确实会有问题，感谢提议的解决方案
