### ISSUE TITLE
是否能让代码片段有独立作用域？

### ISSUE THREAD

**Issue by 0x0042** [laomao800/hexo-tag-demo#2]
假设我有几个相似的例子需要几个类似的代码片段来展示，就会产生作用域问题，是否能考虑引入iframe之类的东西来独立作用域？

**Comment by laomao800** [comment]
这个可以有~

**Comment by laomao800** [comment]
https://github.com/laomao800/hexo-tag-demo/commit/1803d233b7bab08d3c4415e322b9447bb0c4628e

`{% demo %}` 根级的 `<script>` 标签修改为运行于匿名函数内，避免演示代码中的变量污染全局。
